### ISSUE TITLE
"cannot copy directory into itself"

### ISSUE THREAD

**Issue by DarkLordJack** [dashcoin/cryptonote-generator#4]
When running generator.sh I get the following error:
$ bash generator.sh
Updating ...
Already up-to-date.
Make temporary  copy...
cp: cannot copy a directory, ‘/cygdrive/d/gen/generator/generated_files//.’, o itself, ‘/cygdrive/d/gen/generator/generated_files/tmp/.’
Remove temporary files...

system:
Win server 2008 R2 datacenter edition
cmake, boost and cygwin 32bit all newest versions.

**Comment by pmitchev** [comment]
This is pretty strange. I cannot replicate your result. I cannot find any Windows EOL. Can you give example where you encounter it? Maybe it is a problem in older version.

**Comment by pmitchev** [comment]
I fixed a few problems with the generation under Windows and added a detailed instructions about how to install requirement:
https://github.com/dashcoin/cryptonote-generator/blob/master/docs/windows-requirements-install.md

**Comment by DarkLordJack** [comment]
Thanks :)
