### ISSUE TITLE
Scripts using windows line endings

### ISSUE THREAD

**Issue by DarkLordJack** [dashcoin/cryptonote-generator#5]
Many of the scripts included in the repo are using windows line endings instead of unix line endings.

Solution:
run dos2unix on all files edited on windows before uploading.

**Comment by pmitchev** [comment]
Can you give example which file contains windows end of lines? I cannot find any in the current version

**Comment by pmitchev** [comment]
If you are using git-scm for windows it's better to configure it as 'Checkout as-is, commit Unix-style line endings'. You have to use dos2unix otherwise
