### ISSUE TITLE
Error in Python Decoder.

### ISSUE THREAD

**Issue by Biostasis** [dashcoin/cryptonote-generator#9]
Hi,sorry for my bad english,but i am really not into coding,so can you please explain me how to fix this:
Traceback (most recent call last):
  File "lib/environment_variables.py", line 31, in <module>
    config = json.load(json_data)
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 11 column 46 (char 290)

I understood there is some problem with file environment_variables.py,but i don't know how to fix this.Can you please explain?

**Comment by pmitchev** [comment]
If you are trying to create a new coin you have to create a config file first. You can generate some of the examples with the command:
```
bash generator.sh -f YOUR CONFIG
```
If you try to generate Dashcoin the command is:
```
bash generator.sh -f examples/config_dashcoin.json
```

**Comment by Biostasis** [comment]
My config.json giving me error,but config from examples working just fine.

**Comment by Biostasis** [comment]
Oh,no error more,but i get new error while compile.(I will translate)
-- Found Git: /usr/bin/git
-- Found PythonInterp: /usr/bin/python (found version "2.7.3")
-- Looking for include files CMAKE_HAVE_PTHREAD_H
-- Looking for include files CMAKE_HAVE_PTHREAD_H - not found.
-- Could NOT find Threads (missing:  Threads_FOUND) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/urushihara/generator/generated_files/genesis_tmp/build/release
fatal: No names found, cannot describe anything.
CMake Warning at src/version.cmake:3 (message):
  Cannot determine current revision.  Make sure that you are building either
  from a Git working tree or from a source archive.


cc1: ошибка(error): -Werror=maybe-uninitialized: no option -Wmaybe-uninitialized
cc1: ошибка(error): unrecognized command line option «-std=c11»
make[2]: *** [external/miniupnpc/CMakeFiles/upnpc-static.dir/igd_desc_parse.c.o] Ошибка 1(error 1)
make[1]: *** [external/miniupnpc/CMakeFiles/upnpc-static.dir/all] Ошибка 2(error 2)
make: *** [all] Ошибка 2(error 2)
Remove temporary files...

**Comment by pmitchev** [comment]
Sorry for the delayed reply. I've fixed this bug. I've also made a dependencies installer. Run the following line to install dependencies:
```
bash configure.sh
```

**Comment by floerer** [comment]
@Biostasis  How did you fix the first error you got? because I have the same error and I tried to fix it but nothing worked. already tried a couple times to recreate config file but it didn't help

**Comment by Prbcoin** [comment]
Good evening, I have a problem that I have not been able to solve, it is in Windows, since when I run the command, I get an error $ generator.sh -f config_example.json
  File "lib / environment_variables.py", line 11
    print "export" + str (prefix) + str (key) + "= (+" ".join (json.dumps (str (item)) for item in value) +)"
          ^
SyntaxError: invalid syntax
Remove temporary files ...
I already installed the dependencies that they say in the instructions but, it does not come out as expected,
I have tried to find a solution but I have not succeeded I hope you can help me.
